[licenses]
version = 2
private = { ignore = true }
confidence-threshold = 0.93 # We want really high confidence when inferring licenses from text
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0"
]
exceptions = []

[bans]
multiple-versions = "allow"