[licenses]
version = 2
private = { ignore = true }
confidence-threshold = 0.93 # We want really high confidence when inferring licenses from text
allow = [
    "Apache-2.0",       # https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)
    "MIT",              # https://tldrlegal.com/license/mit-license
    "Unicode-DFS-2016", # https://spdx.org/licenses/Unicode-DFS-2016.html
]
exceptions = []
